export const Colors = {
  primaryColor: '#3D3D3D',
  secondaryTextColor: '#E2E8F3',
  secondaryColor: '#3C91E6',
  white: '#ffff',
  buttonColor: '#E2E8F3',
  lightblack: '#6b6b69',
  black: '#000000',
  textGrey: '#2E3E5C',
  textLigtGrey: '#9FA5C0',
  borderColor: '#B6B5B5',
  grey: '#c9c9c9',
  red: '#f52307',
  silver: '#ede3e1',
  placeholderTextColor: '#9BA9B1',
  dotColor: '#ED6E56',
  lightWhite: '#f8f8f8',
  lightBlue: '#F9FCFF',
  deepBlack: '#000000',
  lightBlack: '#B1B1B1',
  textYellow: '#FEB200',
  backgroundColor: '#f0f3f7',
  tabIconSelected: '#D47F2B',
  tabIconDeSelected: '#6B6B6B',
  drawerBackgroundColor: '#5D5D5D',
};

export const Icons = {
  facebook: require('../assets/icons/facebook.png'),
  apple: require('../assets/icons/apple.png'),
  google: require('../assets/icons/google.png'),
  back_arrow: require('../assets/icons/back_arrow.png'),
  menu: require('../assets/icons/menu.png'),
  checked: require('../assets/icons/checked.png'),
  unchecked: require('../assets/icons/unchecked.png'),
  cross: require('../assets/icons/cross.png'),
  no_internet: require('../assets/icons/no_internet.png'),

  filter: require('../assets/icons/filter.png'),
  settings: require('../assets/icons/settings.png'),
  profile: require('../assets/icons/profile.png'),
  jobs: require('../assets/icons/jobs.png'),
  calendar: require('../assets/icons/calendar.png'),
  search: require('../assets/icons/search.png'),
  tick: require('../assets/icons/tick.png'),
  arrow_right: require('../assets/icons/arrow_right.png'),
  plus_white: require('../assets/icons/plus_white.png'),
  arrow_next: require('../assets/icons/arrow_next.png'),

  arrow_down: require('../assets/icons/arrow_down.png'),
  share: require('../assets/icons/share.png'),
  plus: require('../assets/icons/plus.png'),
  info: require('../assets/icons/info.png'),
  arrow_prev: require('../assets/icons/arrow_prev.png'),
};

export const Fonts = {
  DMSans_BoldItalic: 'DMSans-BoldItalic',
  DMSans_Bold: 'DMSans-Bold',
  DMSans_Regular: 'DMSans-Regular',
  DMSans_Medium: 'DMSans-Medium',
};
